### ISSUE TITLE
New CTF variants

### ISSUE THREAD

**Issue by Llizard** [transhumandesign/kag-base#100]
1) Only one team has the flag, the other team has to capture it within a certain time limit.                                   
2) Only one flag (or treasure) is in the middle of the map in a castle and the two teams have to fight for it.
3) Each of the teams has to build a destructable trophy and then deliver it to the enemy base. Lika an anti-CTF.

**Comment by suzumiyasmith** [comment]
Good idea, especially the 2nd one.
It would be fascinating fighting inside the castle. I cannot wait anymore.

**Comment by norill** [comment]
all this can be done already with accordingly designed maps. not sure about 1 - if it's possible to have 0 flags  on one team and not lose instantly. 2 can sort of be done by placing both team flags in the center. 3 can be done by placing flags in reverse - blue flag in red base and vice versa. though you would have to return own flag before "capping"

**Comment by FuzzCat927** [comment]
Instead of having these be separate "CTF Variants", they should just be designated gamemodes, with entirely new scripts and rules.

**Comment by Vikhenzo** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it has not gained enough community traction, or no one has the time to implement this.

Please open a new issue if you would like to refine the idea. You can also contribute directly by making the changes yourself and making pull request – We appreciate your interest in KAG.

Thank you! :)
