### ISSUE TITLE
Avoiding horizontal platforms

### ISSUE THREAD

**Issue by GoldenGuy** [transhumandesign/kag-base#103]
to do this you need to walk towards platforms and do some small jumps. Video shows how op this is: 
https://youtu.be/Rqu2X2qsfjk

**Comment by AsuMagic** [comment]
If you set `g_debug 1` you will notice that, as platforms are tile blobs, the front side of the platforms in your video will be made of 3 separate lines. So I think such a fix would be pretty complicated and might need to be done (in order to be clean?) engine-side - dummy tiles or something could be made to support it better perhaps?
I can't think of a clean pure script-side solution. I might be wrong, though.

**Comment by norill** [comment]
try making the lines a little bit longer so there is a very small overlap

**Comment by 1bardesign** [comment]
@norill that's actually quite a good idea, but it doesn't quite fix the issue (even with a full "pixel" of overlap) - which leads me to think it's possibly caching related. A solution may be not caching collision results for platform colliders, or caching everything except the platform result. Would incur a performance hit for sure though.

@AsuMagic is right that it'd be probably "best" solved in-engine; either through the caching changes above or dummy tile collision options could definitely be extended somehow to handle this - but I've got a feeling (from how the tilemap code works) that the latter would not be a particularly quick/easy fix.

**Comment by Harrison-Miller** [comment]
Fixed in test build.
