### ISSUE TITLE
Full screen on default, and fix screen bug resolutions

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#105]
Make kag Full screen on default with resolutions you can choose.
Repair full screen bugs when you minimize kag.
( important to check discord / steam work when you minimize when applying this fix)

**Comment by FuzzCat927** [comment]
you can already choose resolutions, but I am very much frustrated that KAG sometimes turns to a black screen if you alt+tab / minimize kag while fullscreen

**Comment by Coroz** [comment]
Yes i know you can already choose resolutions, i just say it this way so if they do update to full screen default that we still have that option.

**Comment by AsuMagic** [comment]
Fullscreen by default is a sane idea, although fullscreen bugs are really mostly Irrlicht related issues.  
We should have borderless fullscreen for KAG as most games do instead of exclusive fullscreen, which causes most of the issues you can get on Windows. However Irrlicht doesn't really allow that directly, the only way we could implement that I can think of is to hack native handles out of the Irrlicht API and deal with the OS directly.

**Comment by Vikhenzo** [comment]
I'm closing this issue because it has been over 4 months without acitvity. As Asu said default fullscreen is _viable_ but is not intrinsically better than windowed by default. Besides, there's problems in the mac version with fullscreen and IrrLicht generally doesn't like it very much appareantly.

Please open a new issue if you would like to refine this idea. You can also contribute directly by making the changes yourself and sending a pull request – We appreciate your interest in KAG.

Thank you! :)
