### ISSUE TITLE
Resupply bug Official CTF

### ISSUE THREAD

**Issue by Coroz** [transhumandesign/kag-base#1174]
Bug where you get a 2000sec resupply timer in CTF.

You have to actually wait for 2000sec before getting resupplied again.

How this happens? no idea 😐 
Seems to happen quite a bit.

Build 3580 ish

**Comment by mugg91** [comment]
On a related note sometimes when a new match starts and I start out as builder, I receive no materials. When going back to the tent I notice the resupply timer and I have nothing in my inventory. 
Played on Small CTF server.

**Comment by mugg91** [comment]
I noticed this behavior:

- I'm archer and I'm at the tent or archer shop. I receive arrows and the resupply timer is shown, starting at 20 seconds left.
- The resupply timer runs down, let's say it's at 10 seconds left.
- I switch to builder. Now I get wood and stone and the resupply timer is reset back to 20 seconds.
- Now you have to wait those 20 seconds before you can get builder resupplies AND archer resupplies.

Shouldn't the resupply timer be handled separately between each class. I think there are more bugs related to this. Sometimes I have to wait up to 40 seconds. Sometimes I get 300 wood and 90 stone in one go, instead of 100 wood and 30 stone.

Also, it seems I start out with different amounts of builder materials each match (CTF). It doesn't look consistent.

**Comment by laws65** [comment]
#1154 probably fixes that

**Comment by mugg91** [comment]
I had the 3000 second thing happen now.

I played CTF EU and quit, then played TDM EU for about an hour. Then I joined CTF EU again and as soon as I spawned it said 2702 seconds left.

**Comment by bunniewormy** [comment]
Modified #1154 to include a fix for this

**Comment by mugg91** [comment]
Probably can tick this off as fixed since it hasn't happened since the 2022 build.
