### ISSUE TITLE
Fireplace being re-ignited

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1206]
I extinguished a fireplace and then tried shooting it with fire arrows, but it doesn't ignite.

So I think it would be cool if it was possible to ignite it again with fire arrows.

Perhaps it's also an idea to make a builder be able to re-ignite a fireplace.

**Comment by mugg91** [comment]
Ok, I found out few minutes later that a fireplace can in fact be re-ignited if you place a wood background on it and then shoot that with the fire arrow. 
So at least there is a way, but it's not so straight-forward. 
I let you decide if my suggestion still has worth.

**Comment by eps0003** [comment]
I think I purposefully didn't allow any arrows to collide with campfires because that would be annoying for archers shooting near them. There are two alternative ways this could be implemented:

1. Reigniting it when a fire arrow is stuck on top of the block underneath the campfire.
2. Reignite it when a fire arrow passes through a campfire

**Comment by mugg91** [comment]
Yes, either one of those would be more straight-forward than it requiring a wood background, I guess.
