### ISSUE TITLE
Feature Pitch: bomb bolt upgrade in TTH?

### ISSUE THREAD

**Issue by AcrylicOracle** [transhumandesign/kag-base#128]
Ballistas aren't that powerful until you get the bomb bolt upgrade. leaving bomb bolts out of Take the Hall basically ruins the whole purpose of them, since halls are already more useful spawns then ballistas. I've tried fixing that but i'm stuck somewhere. Halp

**Comment by AcrylicOracle** [comment]
nope, tried but i can't find a solution. it would be a feature, adding bomb bolts to tth, however it's more of activating a simple switch, as i've discovered before. how to activate the switch, i don't know. then the ballista.as file checks for if the switch is turned on, and if it is, it expends double the ammunition but in return shoots a seperate projectile.

**Comment by 1bardesign** [comment]
Not quite sure where you're going on but I just tested this and it works as designed.

- Start TTH server
- Get ballista tech
- Get bomb ammo tech
- (techs look like [this](https://i.imgur.com/S0HjP9J.png) if done with research rather than scrolls)
- Make a ballista using factory (must be done _after_ bomb ammo tech researched)
- Ballista shoots bomb bolts ✔️ 
- Ballista factory makes more bolts ✔️ 

Closing this as a result, you can test it yourself and see.
