### ISSUE TITLE
Getting inside a Crate while moving is too hard

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#1545]
## Current in-game behaviour.

Stand anywhere, hold a Crate, have the mouse cursor pointed in the far sky. 
Then show buttons and let go in quick succession (= "Tap").
Notice that you will get inside the Crate. 👍

Hold a Crate and climb your team's fortress and bounce yourself off with a trampoline.
Furiously spam "show button" but you will never get inside the Crate until the moment you landed.

## Proposed Change

Make Tapping work even when you are moving through the air at high speed.

**Comment by mugg91** [comment]
I have had no problems getting into crates while moving at high speed. My cursor can be anywhere - as long as I'm tapping, I will get into the crate I'm holding.

**Comment by mehwaffle10** [comment]
I have a rework for my balance mod that uses attachments instead of inventories for players. They're also reusable, auto pickup when getting out, and I've swapped getting in/out to space (which utilizes the activation commands) and emptying to e. Fixes issues with controls and warping, may be worth considering parts of if not all for vanilla.
