### ISSUE TITLE
please add CParticle.offset and change CParticle.fadeout to a float

### ISSUE THREAD

**Issue by Shadowblitz16** [transhumandesign/kag-base#177]
please add CParticle.offset so rotations and transforms can be offseted in CParticle
and change CParticle.fadeout to a float to that you can adjust the amount it fades out over time.

**Comment by 1bardesign** [comment]
This sounds a lot like you should write your own particle code using the new rendering functions.

`CParticle` does not properly support soft alpha transparency, and rotations are specified in a non-standard way that means a rotation offset would be slower and all particles would pay the memory cost for something that's not used (you could just offset the texture if you _NEED_ it); you are better off writing the code that you need rather than waiting for `CParticle` to be modified for your convenience, as it's unlikely to change much.
