### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DVSoftware** [transhumandesign/kag-base#183]
I know KAG is a commercial game (which i bought several years ago), and i didn't even realize the assets where publicly available, but I'm wondering what is the license for the assets? 
Can they be used for creating a new game, with crediting KAG of course?

**Comment by 1bardesign** [comment]
At this stage, we haven't formalised any permissive open source licensing because we feel that it is quite unlikely to be generally useful code, as it requires the KAG engine, is written in angelscript, and is honestly often suboptimal or buggy.

As such the licensing only covers using existing code to contribute to the game or for the purposes of mods; though we [explicitly allow](https://github.com/transhumandesign/kag-base#legal-considerations-and-licensing) contributions to be used elsewhere.

If you have a specific use case in mind we are open to discussing licensing the code, however.

If we go with a permissive license for any of the code we are likely to go with MIT or BSD 2 clause unless otherwise required.

**Comment by DVSoftware** [comment]
I'm specifically interested in assets such as images and sounds, code wouldn't be useful without KAG, as you said.

I'm no artist, but want to create a game, and the assets would perfectly fit what i want to create (kind of a sandbox), at least for the prototype/alpha stage.

**Comment by 1bardesign** [comment]
Unfortunately the art/sound assets are not available for free; they are the property of THD.

That said, we generally allow them to be used for non-commercial work if they link back to KAG (ie we wont DMCA for non-commercial hobby projects), but for anything commercial you will need to pay an artist for unique art of course. In that case do _not_ forget to replace them when the time comes though!
