### ISSUE TITLE
Maths::Ceil() doesn't work correctly

### ISSUE THREAD

**Issue by mugg91** [transhumandesign/kag-base#2009]
## Description

`Maths::Ceil()` seems to return the same result as `Maths::Floor()`.

`print(""+Maths::Floor(11/3))` --> 3
`print(""+Maths::Floor(4/3))` --> 1

`print(""+Maths::Ceil(11/3))` --> 3
`print(""+Maths::Ceil(4/3))` --> 1

I expected `Maths::Ceil(11/3))` to return 4 and `Maths::Ceil(4/3))` to return 2.
It is supposed to return the closest higher or equal integer number.

`Maths::Ceil()` is currently used in 8 files. One should check them for errors.

**Comment by asumagic** [comment]
`11/3` is integral division, so its value is already `3`, so `Maths::Ceil` makes no difference. It's not a bug in the API.

To do the division in floating-point so that the `Ceil` is meaningful, you would need to do something like `11.0/3`. (If either of the operands are float the other operand will be cast to floating-point.)

**Comment by mugg91** [comment]
Thank you @asumagic.
