### ISSUE TITLE
Crates with siege weapons must be picked up while unpacking

### ISSUE THREAD

**Issue by TheCatWiz** [transhumandesign/kag-base#212]
Very small change, but it should prevent people from unpacking siege weapons by accident when they try to buy something from shops.

**Comment by bunniewormy** [comment]
going to be a problem sometimes - for example, you couldn't leave a ballista on the ground to unpack and then go protect it from the enemies.

**Comment by TheCatWiz** [comment]
Usually you make safe place for siege before unpacking it, or get one or two teammates to defend it. Also self-assembling ballistas seem kinda weird to me.

**Comment by bunniewormy** [comment]
can't really make safe space or get any teammates to help when you just stole a ballista from the enemy base

**Comment by TheCatWiz** [comment]
Setting up a spawn point right in enemy base shouldn't be easy.

**Comment by bunniewormy** [comment]
people who let enemies steal their ballista that easily should suffer consequences. plus it's not even easy: you need to get to the enemy base first, steal a ballista that will often be protected by a bit of blocks, and protect it enough so that it will unpack and some teammates will spawn on it, and then it's still probably goign to get killed really fast. with this change its just going to be near impossible if there's an enemy near, especially if moving stops the unpacking. I would honestly rather change it so you can't have it picked up if you want to unpack, solves some of the misclick problems (for example using tunnel while holding a crate) + it makes more sense

**Comment by TheCatWiz** [comment]
> people who let enemies steal their ballista that easily should suffer consequences

If people let others steal their ballistas easily, they will lose even without enemy siege on their base.

> I would honestly rather change it so you can't have it picked up if you want to unpack

Maybe.

**Comment by 1bardesign** [comment]
Closing this in that case 👍 Thanks for the discussion.
