### ISSUE TITLE
Gold auto-pickup

### ISSUE THREAD

**Issue by Frankulushus** [transhumandesign/kag-base#288]
Currently when gold is ran over it is auto picked up into the inventory just as wood and stone does, however there is no practical use for gold below stacked below 50.

Given the layout of gold in maps and scattering of materials around mid in populated CTF matches it is simply too easy to unintentionally pick up a stray piece of gold ranging between the values of 4<48 filling one of four builder slots which could have been supplied with up to 500 of other building materials. 

Before you say "this issue is too minor and not worth our time" remember little, key annoyances like these need to be refined for an overall more enjoyable experience particularly for offensive builders. 

I propose that gold under stack 50 should be manually picked up whilst all gold 50 and over should be automatically picked up.

This will not be a toggle on or off system.

Personally I think this will create a further streamlined approach to building, comments are encouraged.

FG

**Comment by eps0003** [comment]
But what if there’s several stacks of gold with less than 50 gold in each. Wouldn’t you want to auto pick them up to form a stack large enough? People may get confused if they expect to auto pick up a stack of gold but it doesn’t since it’s too small. 

I think it should be one or the other: auto pickup or no auto pickup. Since it has pickup priority over other mats, I don’t think it’s difficult to manually pick it up if we instead disable auto pickup. This will ensure builders don’t auto pickup unnecessary pieces of gold and allows them to easily manually pickup gold over other mats.

**Comment by Frankulushus** [comment]
> But what if there’s several stacks of gold with less than 50 gold in each. Wouldn’t you want to auto pick them up to form a stack large enough?

If they have gold collected in their invent prior to running over small stacks it should get collected when ran over.
