### ISSUE TITLE
Repairing for builders

### ISSUE THREAD

**Issue by HappySheepo** [transhumandesign/kag-base#320]
Hello there, it's Sheepo, and i've come up with an idea, i'd like to see what you think about it. :)

Until now, when you are playing builder, you can destroy wooden or stone blocks with your right click, getting 1 resource per hit.

My idea is to implement the option to repair a block with your left click, so you do the other way around (spend 1 resource per hit). This way you won't spend 10 wood or stone in repairing a block, 

To avoid rat builders to stale the situation, i would make the repairing system to be twice slow than destroying (or 1.5 slower).

Thanks for reading the post!

**Comment by eps0003** [comment]
This would be extremely slow and tedious. It would be better just to destroy the block and spend 10 material to replace the block. The current mechanics work perfectly.

**Comment by Shylie** [comment]
repair "already exists" -- you can place undamaged wood over damaged wood, same for stone

**Comment by benjamingorman** [comment]
Agree with what eps said. The default behaviour should not change because most of the time the speed of replacing instantly would be preferable to the resource efficiency of repairing.

But there's no reason not to give more options to players. The suggestion seems sensible and has some good use cases. Could help when walling off rats in a tunnel since the wall could be efficiently repaired. Also perhaps wooden door or platform repair is easier to code than replacement?

Repair could be shift+left click?

**Comment by HappySheepo** [comment]
> This would be extremely slow and tedious. It would be better just to destroy the block and spend 10 material to replace the block. The current mechanics work perfectly.

In case you don't have many materials available but you are in the middle of the map, you can repair small pieces.

> repair "already exists" -- you can place undamaged wood over damaged wood, same for stone

But it's really expensive.
