### ISSUE TITLE
[Feature Pitch] Bring back arrow collisions 

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#335]
My suggestion is to bring back arrow collision. In old KAG, if you shot an arrow at an incoming enemy arrow, both arrows collided and destroyed each other. This could make archer combat richer and make it possible to defend yourself against other archers as an archer.

Also, in my opinion, you should also be able to destroy enemy arrows if you shoot the side of the enemy arrow (so not exactly how it worked in earlier KAG):
![image](https://user-images.githubusercontent.com/39147836/50491947-37e73100-0a15-11e9-929b-4abbfbfad1f6.png) like this

**Comment by Franrek** [comment]
This is probably the most retarded feature pitch so far (including quarries)
Adding defensive ability to main archer attack is incredibly stupid since you will "defend" yourself and hit enemies arrows by accident 99% of times. As an archer in archer duel you pretty much shoot arrows whenever you can in direction of another archer. That means you have some % chance to avoid damage even if enemy was accurate. Game mechanic that is mostly (or even 20% of time) used unintentionally is a bad mechanic. We don't even have to speculate if it will be like that coz we already saw it like 2 years ago.

That change also gives spamming quarter-shots from above huge buff since no archer that is below you can hit you without hitting your arrows.

I have no idea what do you mean by "making archer combat richer". It will be just random damage avoiding all the time and one cool play every 2 weeks.

The only reason why this is upvoted coz it sounds cool. Who wouldn't want shot an arrow enemy arrow in the air mlg style right? :DD Pls, don't ruin best dueling class in KAG. I'm not saying it wouldn't require skill at all anymore but it would be much more annoying for sure.

**Comment by butterdome** [comment]
hey do you know towerfall accention? in the game arrows collide but they dont destroy each other. Both arrows fall down and at a certain speed they do damage again... would that be an option?
