### ISSUE TITLE
Remove saw bombjump

### ISSUE THREAD

**Issue by HappySheepo** [transhumandesign/kag-base#347]
Remove this thing. It is op and should have been fixed years ago.

**Comment by Blubahub** [comment]
@HappySheepo I see no reason to remove besides "people keep killing me with it, let's remove it." You don't state any reason why we should remove it. Removing features left and right is never a good thing.

@eps0003 Theoretically, but then you'd mess up normal bombjumps and parkouring in general. Unless you mean saw bombjump velocity only? I'm not so sure about capping velocity is good in this case, since the OP just wants saw jumps to be totally removed...

**Comment by HappySheepo** [comment]
Nerf it then, but it's retarded how people can travel all around the map with that.

**Comment by Panky123** [comment]
@Blubahub it is a feature in the same way counterjabbing and crouching when shielding is. Translation it appears buggy, is objectively unfair, and there is a history of it being treated as a bug(the most blatant being theflare being banned for "bug abusing" in Auslandia)

**Comment by vicenteferrari** [comment]
I don't mind it.

**Comment by eps0003** [comment]
Closed due to overwhelming negative response.
