### ISSUE TITLE
Precise Jab and Shield Aiming [Change Request]

### ISSUE THREAD

**Issue by xInternetDogx** [transhumandesign/kag-base#486]
Currently Jabbing and Shielding have locked ranges for where their hitboxes appear based on where your mouse is rather than them moving exactly with where your mouse is.

I would like to propose the hitboxes of the jab and shield each not be bound by ranges of mouse motion and instead have the hitboxes based on the precise position of your mouse.

Shields' hitbox would work freely the same as a knight slash does. Jabs' hitbox would work similarly, but still be locked to a single angle after the initial click.

I understand that slashes have sprites that work in a full 360 degree range, but I do not believe making this change to shields and jabs would bring any visual issues. This is because the sprite animations would still trigger in the same range that they normally do.

Here is a video demonstrating the current locked hitboxes for jabbing:

https://youtu.be/Pf5uzNasrl8

**Comment by Harrison-Miller** [comment]
I don't think unlocking the rotation of shielding/jabbing is a good idea. It'll lead to a lot of visual oddities or misunderstandings of what is actually happening in the game especially without animations to account for the new angles + as your video shows the current jabbing/shielding gives an arc of hit rather than a single point and those arcs account for all possible angles.
