### ISSUE TITLE
Optimize GUI functionality

### ISSUE THREAD

**Issue by AsuMagic** [transhumandesign/kag-base#507]
**Describe the feature**

As of now GUI functions are really inefficient, including text and icon rendering. Ideally there should be batching for these, but this may prove difficult to implement.

**Additional context**

The above problem causes scoreboard rendering to be horribly slow especially with many players, which does get worse as we add things like accolade, player heads, assists column, etc.

GUI (in general, including pure script tmes) can also take a significant part of the rendering time, which can be as high as 1/3 of the CPU time.

**Comment by mugg91** [comment]
Just saying that I'm having a small issue with the scoreboard, so I don't have to flood the github with a ton of small issues. :stuck_out_tongue: 

So if there are many players and I want to hover mouse over badges/accolades of the players listed at the top in blue team, the scoreboard scrolls up. Since the information is displayed below the scoreboard, it cannot be seen. The tooltip information should instead be displayed next to your mouse cursor.

https://i.imgur.com/P8ouSRh.jpeg - I cannot see HOMEK kagcheats.com's accolades information.

**Comment by AsuMagic** [comment]
GUI performance is (mostly) a solved problem in staging.
