### ISSUE TITLE
[Feature Pitch] Balance teams by account age

### ISSUE THREAD

**Issue by Mazey** [transhumandesign/kag-base#513]
From `a crab#4171` via Discord, expanded.

**Feature Pitch**

With free to play, there are often unbalanced teams, because the majority of players are either new to the game or have played the game for several years, there is a fat chance one team will have far more inexperienced players. This should be fixed by balancing teams based on account age on nextmap and when someone joins the game.

Codewise:
- On nextmap: sort all players by age, then, in turn, put the oldest player who is not in a team on the blue or red team.
- On player join: If the teams are equal in size or there is 1 player difference in size, calculate the total age of each team and put the new player in the team that has the lowest total age.
- Modify autobalance so it allows for a 2 player difference in team sizes unless there is a significant margin between the team's total age.

**Comment by AsuMagic** [comment]
I think it would make more sense to compute a score which depends on the usefulness of a player and is more sophisticated than the KDR.
Balancing would make much more sense then. You can still have huge skill gaps in older players.

**Comment by Mazey** [comment]
Creating a hidden score would be much harder because of builders and archers, age is far more simple and should be fairly accurate (and `6Y + 4Y + 4 x N` vs `7Y + 5Y + 4N` should already improve a lot)

**Comment by eps0003** [comment]
Age is a poor indicator of skill. There are many 7-year gamers who have recently returned to KAG and are bad at the game. Most good players nowadays have an account age of 3-6 years.

**Comment by Erbenos** [comment]
Wouldnt it be better to use coins earned as skill indicator? It basically already rewards players by being productive.

**Comment by Omen267901** [comment]
Age is a terrible metric, due to the simple fact that a LOT of old veterans who haven't played in months or maybe even years are coming back for the f2p launch. There's a good chance these players are only marginally better than a new player due to how long it's been since they played, and weighting them higher would just make the problem worse.

Speaking from the perspective of one of these old veterans who haven't played in years, I'd hate to weigh my team down because I blocked an actually good player from joining our team.

**Comment by Erbenos** [comment]
At the start of the round AND when the player joins the match of course. Even mid-round, with possibility of some maximum autobalancing frequence threshold? No idea, dind't see the code.

**Comment by MatheusGodoi** [comment]
Coin earned not much accurate too tbh, a really good knight can get alot of coins, but a builder spamming blocks behind the tent and a archer not moving in the flag door shoting outside can earn the same amout maybe faster with less risk of dying and loosing it, the KDR would be more precise, and now with the assist feature it could be more accurate imo

**Comment by Erbenos** [comment]
Wouldn't it be possible to scale the weight of coins based on class played then?

**Comment by Omen267901** [comment]
> Wouldn't it be possible to scale the weight of coins based on class played then?

Assuming that Archer and Builder would be weighted less than knight, this would punish builders who actually build decently and who push enemies, and I'm not even sure how you would handle archers since they're a support class. There's no clean way to handle a reduction as far as I can tell.

I'd be worried KDR would lead to builder/archer mains not being weighted high enough since builders obviously don't get many kills and archers typically get less kills than knights unless enemy team has bad knights or builders aren't covering themselves/their archers.

**Comment by MatheusGodoi** [comment]
then a very good archer would be weighted the same as an average knight if done poorly
kdr seems the most constant thing to be used

**Comment by Panky123** [comment]
Let's be honest here, try to actuallt balance teams without statistics that rank the entirety of the player(kdr, wins, losses, ECT) is an exercise in futility and a waste of time. Kinda like editing the wiki 😃

**Comment by Shadowblitz16** [comment]
NO I have 6-7 years of kag experience but I am no better then a moderate player most of the time
