### ISSUE TITLE
Armour Station

### ISSUE THREAD

**Issue by xXIlluminatiPartyXx** [transhumandesign/kag-base#547]
Heres a suggestion: Armour. If a friendly builder decides to make an armour station for a high cost its knights lucky day. Builders deposit stone and gold into the station and knights can use it to produce different armours. Armours increase health but slow move speed, some armours increase your move speed but slow attack speed.

Even archers can use it a bit, but they can only make hats which buff certain types of arrows and debuff others. Hope you like my idea!

**Comment by blackjoker77777** [comment]
This reply is regrading #545 #546 and #547 .
Not to be rude, but just being realistic.
Your ideas are quite good when it comes to having them implemented in some mods (*and someone at some point, would be interested in making them come true*), but when it comes to the vanilla game.. that's probably a bad idea, and mostly would never happen.

Here are the three main reasons for that:
1. KAG is skill-based (ping and luck count, but let's leave that off the table for now).
When some player fights another one, they should have the same stats, you can't judge which one is the best knight if someone had a higher slashing speed or the other a better knockback effect.

2. Adding custom things to buff some stuff, would encourage the lone-wolf mentality, and people would try to Rambo-kill the whole enemy team on their own, and that is bad. In fact, very bad, since the whole game is based on team-work.
Some people are being rude to their teammates and consider them useless, we need to change that, not encourage it.

3. Adding these would make the game unbalanced, and the development team would be forced to nerf A and buff B to make sure C isn't broken, whereas the community would keep complaining.. again.. and again. 
We (*as a community*) are still trying to make sure everything is in an "acceptable" state (hence why PRs are getting added on a daily basis), adding more things to the plate isn't the wisest move. 

Your ideas are creative, and I'd love if you could share them on the #modding channel on discord (https://discord.gg/kag), I believe someone might be interested in working on them. :)
