### ISSUE TITLE
Particles

### ISSUE THREAD

**Issue by xXIlluminatiPartyXx** [transhumandesign/kag-base#548]
An idea I was thinking of are some kind of particle effects gotten from being good at kag. They dont buff your character, only make partially see through particles which float around your character and look awesome.

These could be gotten from achievements or something and can be traded. Anyone who previously purchased the game will have a shiny particle effect on their tools, to make it look more golden.

**Comment by blackjoker77777** [comment]
This would make it much worse for players with bad/moderate hardware (myself included) and cause even worse fps drops. 
Aside from the fact that having a bunch of shiny things on your screen while fighting would probably just distract you from the battle.
Particles floating around you would ruin the "hiding behind a bush", "pretending the be dead" and "digging a tunnel secretly" strategies as well. It's just as if you're having a lantern, that throws glitter everywhere, hidden inside your inventory.

Also..
>particle effects gotten from being good at kag.

Being good in KAG is relative, since there's always people who are better than you, so practically no one is actually "good"..

**Comment by xXIlluminatiPartyXx** [comment]
Don't worry! They wont show in tunnels or if you are crouching! If the lag is too high they can stop too. And by good I mean a point where you have a certain amount of achievements
