### ISSUE TITLE
One time buy DLC

### ISSUE THREAD

**Issue by xXIlluminatiPartyXx** [transhumandesign/kag-base#554]
I know that stable income is the way to go and this is how I propose that we please both parties. I believe that custom heads and cape should become one time buys with cape for about $12 and the custom head for about $25. This is because some people even though they want to support the game as much as they can, do not have the sort of money or time to invest $20 or $10 a month. Instead I think that for the round table and the royal guard you should have access to a special costumes menu and discord chat.

With the costumes menu you can change some of character to include a costume which will increase the diversity and fun. I would like to see lots of other DLC because the more DLC the more money you guys receive.

Some other ideas for DLC would be new campaigns and singleplayer modes along with special servers and access to cool and interesting cosmetics. I hope you like the suggestion!

**Comment by Panky123** [comment]
No one is gonna pay 20 dollars for a discord chat/cosmetics that they have to share. TBH the custom head is the only thing they can offer "worthy" of the tier. To just sell it for 25 dollars might make you happy because it falls in your budget but they have never devalued that customization to that level(used to be reserved for larger sum donations/for large community additions).

**Comment by eps0003** [comment]
Closed due to overwhelming negative response.
