### ISSUE TITLE
Dynamite!

### ISSUE THREAD

**Issue by xXIlluminatiPartyXx** [transhumandesign/kag-base#555]
I have a suggestion for a new bomb type for knights. This new bomb will not be anti player, only dealing 1 - 2 hearts of damage to players, instead it will be used for demolition purposes. It detonates on impact or after a certain amount of air time and heavily damage blocks within 2 blocks and damages more in 4 blocks. It will cost about 30 and it will make taking down forts a bit easier and you aren't trying to take a fort with a small bomb.

**Comment by eps0003** [comment]
I don't think dynamite is a good name for this. How about something like a barrel with a fuse filled with explosive powder, and we just name it "Keg". 🤔

**Comment by Panky123** [comment]
> I don't think dynamite is a good name for this. How about something like a barrel with a fuse filled with explosive powder, and we just name it "Keg".



> I have a suggestion for a new bomb type for knights. This new bomb will not be anti player, only dealing 1 - 2 hearts of damage to players, 

His suggestion reads more like a bomb satchel(which i liked in modded servers but am not sure i would like in general). If you're gonna be snarky you could atleast try to be accurate.

**Comment by MrPotatobird** [comment]
That sounds rather overpowered, and the role of "demolition explosive" is already kind of filled by kegs. I can understand the motivation, because your average knight player doesn't have a lot of demolition independence (they need builders or people to protect their kegs usually) which can feel frustrating. However this solution has issues.

The dynamite as you've described it is cheap, there's little opportunity to stop it because it detonates on impact, and it does way too much block damage. Think about whether it would be fun for builders if knights had bombs with many times the destructive power of bombs, at about the same cost. Structures would get eaten away at way too fast.

**Comment by xXIlluminatiPartyXx** [comment]
alrighty!
