### ISSUE TITLE
Remove gold cost from boat shop.

### ISSUE THREAD

**Issue by Shylie** [transhumandesign/kag-base#573]
**Current in-game behaviour.**

Boat shop costs 50 gold.

**Proposed Change**

Boat shop costs no gold.

**Comment by Omen267901** [comment]
Reasoning? The boat shop costing gold serves a purpose if I had to guess, and I'd like to know if there's a particular reasoning for removing it.

**Comment by Panky123** [comment]
Yea sure the reasoning is the shop isnt worth 50 gold whereas siege, tunnel and quarries ARE. The boatshop is barely useful on water maps and isnt even worth the 50 gold unless you already have quarries tunnel and siege.

**Comment by xXIlluminatiPartyXx** [comment]
ship buff time?

**Comment by AsuMagic** [comment]
Boats being useless is a map issue IMO. Not that it is necessarily a problem. What is the last CTF map you remember that had a lake you couldn't cross with a single bombjump (or didn't have an alternative pathway on top that makes boats virtually useless)? I don't remember any. Even FellereFourRivers (RIP) only had relatively small lakes.  
There was one map in the rotation (and I don't think it's even in anymore) that probably had the largest lake that would classify, but boats were useless because you could destroy them so easily and they didn't really allow for pushing. IIRC warboats are not even respawn points in CTF.

**Comment by blackjoker77777** [comment]
I agree with it being a map issue.
If mappers made bigger lakes and used enough sharks, I bet players would be more prone to buying boats.
Also I'd want to see sharks and bisons get some love..
During some recent iko round, people were confused when they realized that you can tame bisons (also they kept calling them *"cows"*.. :disappointed:); that's probably because they don't see them that much on official maps, which is sad, and should probably change.

> IIRC warboats are not even respawn points in CTF.

I don't know whether that's true or not, but if it is, that must be changed.

**Comment by Omen267901** [comment]
This is definitely a map issue more than anything.

**Comment by MrPotatobird** [comment]
If your map doesn't have a massive lake, then that isn't a problem. That just means your map isn't trash.

The fact that most maps don't have massive lakes that REQUIRE you to make a boat shop is not an issue at all. It's a relief. Even on those maps, if you literally NEED a boat shop to even get to the enemy's crappy island, then why should it demand a resource that you might not be able to get more of?

**Comment by AsuMagic** [comment]
I definitively did not mean that massive lakes would be a good idea. I only showed that boats are useless because lakes are too small for them to be worth it.

**Comment by Shylie** [comment]
It's not just a map issue. Due to boats being transportation, they're more often under attack, and therefore break faster than a siege at the top of a tower for the same price would.
Not to mention that a ballista costs 200 coins whereas a warboat costs 100.

**Comment by Panky123** [comment]
If we are being fully honest dinghies, warboats, longboats dont effect the game the same way tunnels siege and quarries do. Even if it is a full blown watermap the shop isn't worth 50 gold.
