### ISSUE TITLE
Dont count killing yourself as teamkill

### ISSUE THREAD

**Issue by CatWiz** [transhumandesign/kag-base#605]
**Current in-game behaviour.**

If you kill yourself by using explosives (bombs, mines, kegs), game counts it as a teamkill and takes away a ton of coins from the player on top of coin loss on death

**Proposed Change**

As title says, dont count killing yourself as a teamkill

**Comment by MatheusGodoi** [comment]
Yes please! Its so sad loosing so many coins for a mistake, as a professional lagger trying to bombjump always make me go in debt ):

**Comment by Shadowblitz16** [comment]
this sounds like a good feature.
although there should be special precautions to make sure people don't just suicide to save their coins close to death

**Comment by blackjoker77777** [comment]
> although there should be special precautions to make sure people don't just suicide to save their coins close to death

I can't see what you mean.. Could you please elaborate more? 

Whether an enemy killed you or you happened to kill yourself, you'll always lose some coins (death penalty); this issue was related to the fact that accidentally killing yourself counted as well as a teamkill, reducing an additional 50 coins as well. 

So you can't really "save your coins by suiciding" since you'd be punished for dying either way, unless I missed your point. 🤔

**Comment by Shadowblitz16** [comment]
oh I must of misunderstood
