### ISSUE TITLE
MacOS has had fullscreen disabled for YEARS...

### ISSUE THREAD

**Issue by ghost** [transhumandesign/kag-base#61]
It's said it has been temporarily disabled on the setting when you launch the game for multiple years now. Is there a reasonable explanation why this issue hasn't been addressed? Such a basic feature...

**Comment by 1bardesign** [comment]
The explanation is that we have very few OSX users and that they haven't made much noise about this in particular.

Irrlicht, the rendering library we use, and particularly the old version that we are currently stuck with, has some issues with fullscreen on recent OSX. The symptoms included entirely black screen (total rendering failure) so fullscreen was disabled to prevent users from being exposed to this bug.

If you are willing to test this on OSX you _may_ be able to get @AsuMagic to work on this, though I don't think this issue exists on Linux - he has expressed interest in upgrading irrlicht though, and that may fix the issue.

**Comment by Cruplezone** [comment]
@1bardesign Yes of course I would be willing to test. As it is right now, there is no blackscreen when going fullscreen through MacOS' (there is no more OSX) native fullscreen option on windowed mode, but there is visual glitching on the bottom of the screen making it not very enjoyable to use. I understand this could be different from the engine's fullscreen option.

Windowed mode is essentially useless at the moment as the game revolves around mouse movement and if you have 'Hot Corners' setup on your mac they trigger all the time (jumping to desktop, showing mission control, etc.).

If he would be willing to update it and see if it fixes it, I would be willing to test for sure.

**Comment by 1bardesign** [comment]
Well, glad to hear it - it's probably up to him then.

He will have got a notification from this but since he hasn't replied it may be worth jumping into discord (link is in the main menu of the game if you haven't already) and pinging him in the `#development` channel about it. He's in French timezone.

If he's keen to try, then you can apply for tester status (everyone is accepted) and jump in the `#testing` channel to discuss it further.

**Comment by Diprog** [comment]
I'll get a macbook soon, so I will be able to help too.

**Comment by AsuMagic** [comment]
According to MM upgrading irrlicht may be a huge pain and it's not very surprising.  
Even if I would love to have every dependency up to date and left as easy to upgrade as possible, I don't even know if it would be worth upgrading, in particular since a lot of issues may be not fixed in newer irrlicht versions.

I'm not very familiar with irrlicht and within so many years I would except significant api breakage, old custom changes for kag directly applied to the library (= huge pain to upgrade) and _possibly_ dubious usages of the library that breaks in newer versions.

It sucks that we don't really have active developers running macOS (AFAIK), but this is the kind of issue that is annoying to debug and practically impossible to fix without debugging, and I don't have a mac test environment. Sadly I'm not interested into getting mac hardware or spending days on installing a mac vm that might get opengl acceleration broken anyway.  
That's for the bug making fullscreen buggy enough to have it removed, though. I don't know how macOS's fullscreen feature works, but it's already pretty impressive it doesn't break horribly with this engine. I'm curious about how it works (both for the user and in the technical meanin), because then there might be ways to work around the issues you're encountering.

**Comment by AsuMagic** [comment]
I just thought about something... Can you please look up in console logs (or in the console, use page up/down to navigate) if you see a "forcibly resized window" warning when you use macOS's native fullscreen you mentioned?

Again, I don't know how it works, but I actually had an engine PR to have a workaround for the linux build for those who want to use compositor rules to use custom windowed fullscreen like you want to do.

**Comment by AsuMagic** [comment]
One last thing, maybe you would like an option to cap the mouse cursor to the window boundaries in windowed mode?

**Comment by Cruplezone** [comment]
![image](https://user-images.githubusercontent.com/17866415/33090040-96c19fc6-cec0-11e7-9f7a-d5965015ce57.png)

Yeah such a feature would be great.

But in regards to fullscreen, native MacOs fullscreening works great if the windowed resolution is the same as the monitor's. No glitching at all and works fantastic. However, if it is smaller than you get visual glitching on the bottom of the frame near the black bars. Nothing in console that I can see when fullscreen is triggered. It does not actually stretch the game or anything.

**Comment by AsuMagic** [comment]
There's a lot of things we don't have control over and that are handled by irrlicht, the `g_forceresolution` workaround may work if you set it to 1 (when it is released) and set the kag resolution to your display resolution.

**Comment by Blubahub** [comment]
... What happened to this? It needs to be done.

**Comment by 1bardesign** [comment]
Requires upgrade of the library `irrlicht`; it's on the long-term todo but requires a lot of work before it's possible to do, and the tiny number of mac users (according to steam internal stats <2%) unfortunately doesn't make this a priority, even though it's a bad deficiency.

**Comment by Harrison-Miller** [comment]
Mac Support has been dropped.
