### ISSUE TITLE
Remove coin loss from teamkilling

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#644]
Coin loss from teamkilling is the biggest bullshit ever [for the purpose of this issue we are going to ignore the existence of no anims and potatobird's shit maps]. Most of the time you keg 3 enemies and somehow 1 random archer from your team also dies, oh yeah, that means COIN LOSS. Makes no sense to me. Or when you make a spike trap and swap team, your new team keeps killing itself on the spikes and you lose coins. I can't see any reason for this to exist - intentional teamkilling should be punished with a ban/votekick if needed, not with broken coin removal

**Comment by blackjoker77777** [comment]
> [for the purpose of this issue we are going to ignore the existence of no anims and potatobird's shit maps]

cute.

> Most of the time you keg 3 enemies and somehow 1 random archer from your team also dies

they keyword here is **your team**, KAG is a team-based game, you can't just kill one of your own for the sake of killing some enemies because it just goes like this:
I killed my teammate to kill 3 enemies -> I killed a teammate to make sure that *one* OP enemy knight gets killed -> I killed our useless teammate because he was blocking my way and blablabla..
TeamKill coin loss might be too much, that I agree with; but it should exist.

If you actually happened to kill a bunch of enemies and accidentally a friend, your coin gain should theoretically bypass your coins loss, if not: then you scarified your guy and lost your money uselessly, **so you did something wrong and should probably avoid doing it in the future!**.

>your new team keeps killing itself on the spikes and you lose coins.

Make smart fool-proof traps, or get a better team; it's just how it works?

>intentional teamkilling should be punished with a ban/votekick if needed

The vote-kick system has proven not to be that great, since the very start of this game.. so.. I wouldn't really rely on it tbh.

**Comment by Omen267901** [comment]
This is "massively changing a core game system to fix a tiny issue" to the extreme tbh.

**Comment by blackjoker77777** [comment]
it's not really a "tiny issue", losing coins after killing a teammate is **not** an issue; you pay the price for what you did, as simple as that.
The teammate that got killed:
- Lost his progress in the battlefield (now that you killed him, he needs to get back from the tent to that exact spot, which is time-consuming and could be hard).
- Got an additional death (thanks to you, killer) and hence a worse KDR (in case they care about it).
- They need to wait to respawn..
- They lost whatever items they had on them..
- They lose coins, for dying..
- You could be the reason behind ruining their fun.

So yeah, if you kill a team-mate you **should** get punished!

aside from that, there is a real 'issue' that was brought to our attention on the discord which is about making spikes then getting swapped to the other team, any *old* enemy (which is now a teammate) stepping on your traps and dying makes you both pay they price; this should be fixed.

And I'm in favor of reducing the teamkill penalty from 50 coins to anything lower, but totally against nullifying it.

**Comment by bunniewormy** [comment]
> * Lost his progress in the battlefield (now that you killed him, he needs to get back from the tent to that exact spot, which is time-consuming and could be hard).
> * Got an additional death (thanks to you, killer) and hence a worse KDR (in case they care about it).
> * They need to wait to respawn..
> * They lost whatever items they had on them..
> * They lose coins, for dying..
> * You could be the reason behind ruining their fun.
> 
> So yeah, if you kill a team-mate you **should** get punished

all of which could be avoided if he was a good player and actually paid attention.

you're talking like newbies jumping into saws in destroyed team traps, or on spikes, or literally walking into a keg i lit 5 seconds earlier is my fault. this feature punishes you for trying to make progress or hurt the enemies, because of having not good players in team. killed 3 knights and 1 builder with a spike and saved your team's tower? yeah, you're not going to get any coins because some random team archer was also there and tried to 1v4.

but i'm the reason for ruining their fun

**Comment by blackjoker77777** [comment]
First, no need to automatically 👍 anything you post here, your ego doesn't require any size enhancements since it reached its maximum size years ago.
That was a joke, no need to get offended; but I can't take you seriously while doing that tbh.
> all of which could be avoided if he was a good player and actually paid attention.

Fun fact, you weren't born a KAG pro, neither did I. 
People don't know how to play correctly since they're new, you can't blame them for that.. We're trying to attract new blood, not get them keg-ed randomly so that they'd rage-quit the game and we'd end up with the current elitist circlejerk (I bet you'd love that); in the name of you enjoying that "victory".

Also you can't always pay attention, real life happens, too many things on the screen, discord pings and people decide to ring your doorbell when you're in-game which obviously distracts normal human beings.

> you're talking like newbies jumping into saws in destroyed team traps, or on spikes

Yes, because they're new, they die now and decide to avoid the danger the next time; no one wants to keep dying and being yelled at by his team.
They learn stuff, some of them slower than others and you could speed up the process by just mentioning that they should take care in chat, you're playing with humans not fricking illiterate rocks.

> or literally walking into a keg i lit 5 seconds earlier is my fault.

Shit happens.

>  this feature punishes you for trying to make progress or hurt the enemies, because of having not good players in team.

 this feature punishes you for trying to make progress or hurt the enemies, because of **you not caring about your teammates, and always thinking that you're better than them.**

Sangfroid was always a great player, not only skill-wise but also speaking of his attitude, and he'd always be respected; you know why? because despite going lonewolf-style he was modest, he would kill 10 enemies, steal the flag and give it to a new player to enjoy the glory while holding other enemies, 5 seconds later the new guy dies and he just laughs it off and keeps playing. Instead of trying to change game mechanics so that they would suit him, he used to change his strategies accordingly.
What about you try to learn from that? instead of try-harding and going like "bunnie the savior lord that keeps winning games alone, because he thinks everyone else in his team is inferior?".

> killed 3 knights and 1 builder with a spike and saved your team's tower? yeah, you're not going to get any coins because some random team archer was also there and tried to 1v4.

If you had read my last post carefully, you'd have noticed that I explained how I dislike the current -50 coins per TK, I said as well that I'm in favor of decreasing it. But not nullifying it.
So that doing what you mentioned would still bring a significant gain in coins.

> you're trying to win, got a knight shop on top of enemy tower, about to buy a keg, but OH WELL, someone just killed himself in your base at the tree saw. that's no keg for you.

If the tree-saw wasn't well-protected, you should have taken that into account?
if it was that clear and yet he fell in it, then it's ok? because that's the human nature, we do things wrong most of the time? 
if it was protected and your teammate broke it, then kick him for griefing?

> but i'm the reason for ruining their fun...

Fun as I define is: enjoying the game.
Obviously it's not the same term you use, which stands for: winning the game alone, because hail me!

> i don't understand how people actually agree with these arguments? do these people actually ever play kag?

Why do you think they would agree with me if they didn't actually care about the future of this game?
We don't want it to be only populated by elitists and tryhards, that's basically it.
We want a way to **force** people, that give 0 f4cks about other people in their teams, to remember that other people exist? you kill them, you get punished, why is this hard to understand?

Like seriously, it's a game, you need to have fun, with other people, that's the purpose of it ffs..

>  this feature makes absolutely 0 sense

No you are making no sense. 
What feature are you talking about? it's called a TeamKill penalty, it's a punishment, not intended as a nice wuvvy feature, to suit your twisted likings.

> why should i 'care' about my teammates with >0.5 kdr to the point of not trying to kill enemy tower just because 1 guy is jabbing stone doors?

This mentality just proves that such mechanism needs to remain in place, since you and other people don't know how to "care" about your teammates, as long as it's existent you selfishness would remain controlled.. a bit at least.

I have been fed up with this topic because I, @MrPotatobird and @Vam-Jam wasted a couple of hours explaining to you why this is a horrible idea, to say the least. Yet, you keep on chewing the same reasoning over and over which basically is:
>I want to win even if I had to kill all my teammates because they're "retarded" *[sorry for using your favorite term, please don't sue me]*, it's ok if they lose coins, time, KDR and everything because they suck; BUT **I should totally not lose a single coin for doing so**; because it's "for winning's sake" and bla bla bla.

We both know you'd probably never change your opinion unless Geti states that it's flawed, so I'm going to take my chances and tag him here, to see what he has to say about this. @1bardesign (sorry for this, in advance.)

Have a nice day.

**Comment by bunniewormy** [comment]
> First, no need to automatically  anything you post here, your ego doesn't require any size enhancements since it reached its maximum size years ago.
> That was a joke, no need to get offended; but I can't take you seriously while doing that tbh.

I can't take you seriously when you don't even play the game and yet decide to voice your opinion on about everything
> 
> > all of which could be avoided if he was a good player and actually paid attention.
> 
> Fun fact, you weren't born a KAG pro, neither did I.
> People don't know how to play correctly since they're new, you can't blame them for that.. We're trying to attract new blood, not get them keg-ed randomly so that they'd rage-quit the game and we'd end up with the current elitist circlejerk (I bet you'd love that); in the name of you enjoying that "victory".
>

as i said several times, and i need to repeat, these people aren't teamkilled intentionally. they kill themselves and the good players are punished for it. and no, coin loss isn't going to prevent them from getting killed, just hurt the team because the team's carry doesn't have money.

> Also you can't always pay attention, real life happens, too many things on the screen, discord pings and people decide to ring your doorbell when you're in-game which obviously distracts normal human beings.
> 

do you actually consider this a valid argument against removing coin loss? you're pointing out right now that it's not the good players' fault for them dying, and still want to punish them because of the noobs? riduculous, i shouldn't lose 100 coins because 2 archers can't pay attention. what? seriously does anyone think this is a valid argument?

> > you're talking like newbies jumping into saws in destroyed team traps, or on spikes
> 
> Yes, because they're new, they die now and decide to avoid the danger the next time; no one wants to keep dying and being yelled at by his team.
> They learn stuff, some of them slower than others and you could speed up the process by just mentioning that they should take care in chat, you're playing with humans not fricking illiterate rocks.
> 

i don't give a fuck if they die mate, they can die all they want, it's not my fault, i shouldn't be punished for it by losing coins?

> > or literally walking into a keg i lit 5 seconds earlier is my fault.
> 
> Shit happens.
> 

shit happens indeed, no need to remove my coins because of casuals in team

> > this feature punishes you for trying to make progress or hurt the enemies, because of having not good players in team.
> 
> this feature punishes you for trying to make progress or hurt the enemies, because of **you not caring about your teammates, and always thinking that you're better than them.**
> 

you say that they die because of their own fault - being bad and not paying attention - and now you say that i don't care about my teammates? i'm not 'thinking' i'm better than them, i know i'm better than them, which is completely fine - as you said, noone is born a pro. i'm not going to hold their hands all the time and i shouldn't be punished for their mistakes

> Sangfroid was always a great player, not only skill-wise but also speaking of his attitude, and he'd always be respected; you know why? because despite going lonewolf-style he was modest, he would kill 10 enemies, steal the flag and give it to a new player to enjoy the glory while holding other enemies, 5 seconds later the new guy dies and he just laughs it off and keeps playing. Instead of trying to change game mechanics so that they would suit him, he used to change his strategies accordingly.
> What about you try to learn from that? instead of try-harding and going like "bunnie the savior lord that keeps winning games alone, because he thinks everyone else in his team is inferior?".
> 

praising pubstompers that only slashspammed? nice. how is that related to this in any way? yeah you can show off all you want. i'm changing the game mechanics so they don't punish good players for having newbies in team, christ.
> > killed 3 knights and 1 builder with a spike and saved your team's tower? yeah, you're not going to get any coins because some random team archer was also there and tried to 1v4.
> 
> If you had read my last post carefully, you'd have noticed that I explained how I dislike the current -50 coins per TK, I said as well that I'm in favor of decreasing it. But not nullifying it.
> So that doing what you mentioned would still bring a significant gain in coins.
> 

can you tell me first what's the point of coin loss at all? because it surely isn't going to prevent the newbies from dying from their own fault, it's just always going to be an inconvenience which hurts the team's carries

> > you're trying to win, got a knight shop on top of enemy tower, about to buy a keg, but OH WELL, someone just killed himself in your base at the tree saw. that's no keg for you.
> 
> If the tree-saw wasn't well-protected, you should have taken that into account?

yeah but the pro newb destroyed the tree farm and killed himself. my fault

> if it was that clear and yet he fell in it, then it's ok? because that's the human nature, we do things wrong most of the time?

i'm completely fine with that. don't remove my coins because of this

> if it was protected and your teammate broke it, then kick him for griefing?
> 
> > but i'm the reason for ruining their fun...
> 
> Fun as I define is: enjoying the game.
> Obviously it's not the same term you use, which stands for: winning the game alone, because hail me!
> 

the game's goal by nature is winning. others can enjoy the game all they want, why am i supposed to be punished for trying to enjoy the game my way - try to get to the goal of a CTF match, which isn't a 3h defensive cancer stalemate, but a victory?

> > i don't understand how people actually agree with these arguments? do these people actually ever play kag?
> 
> Why do you think they would agree with me if they didn't actually care about the future of this game?
> We don't want it to be only populated by elitists and tryhards, that's basically it.
> We want a way to **force** people, that give 0 f4cks about other people in their teams, to remember that other people exist? you kill them, you get punished, why is this hard to understand?
> 

they kill themselves, i get punished, is this hard to understand? this change would change absolutely nothing regarding newbies, they wouldn't even know about it. 

> Like seriously, it's a game, you need to have fun, with other people, that's the purpose of it ffs..
> 

yeah i'm having fun, with the good players in my team - these which can at least read chat. the purpose of a CTF match is to finish it and win, and i'm having fun with that.

> > this feature makes absolutely 0 sense
> 
> No you are making no sense.
> What feature are you talking about? it's called a TeamKill penalty, it's a punishment, not intended as a nice wuvvy feature, to suit your twisted likings.
> 

it's a broken penalty that doesn't work, due to half of the teamkills being noob teammates' fault

> > why should i 'care' about my teammates with >0.5 kdr to the point of not trying to kill enemy tower just because 1 guy is jabbing stone doors?
> 
> This mentality just proves that such mechanism needs to remain in place, since you and other people don't know how to "care" about your teammates, as long as it's existent you selfishness would remain controlled.. a bit at least.
> 

oh, look, 3 knights trying to get up my tower. oh shit, i cant drop a spike because some archer is afk on the bottom. oh well.

oh, look, 1 random knight stands on top of enemy flag room, oh well, i cant drop a keg because hes probably playing on full zoom in


> I have been fed up with this topic because I, @MrPotatobird and @Vam-Jam wasted a couple of hours explaining to you why this is a horrible idea, to say the least. Yet, you keep on chewing the same reasoning over and over which basically is:
> 
> > I want to win even if I had to kill all my teammates because they're "retarded" _[sorry for using your favorite term, please don't sue me]_, it's ok if they lose coins, time, KDR and everything because they suck; BUT **I should totally not lose a single coin for doing so**; because it's "for winning's sake" and bla bla bla.
> 

they're going to lose coins, kdr and everything either way, because i'm still going to kill them.

> We both know you'd probably never change your opinion unless Geti states that it's flawed, so I'm going to take my chances and tag him here, to see what he has to say about this. @1bardesign (sorry for this, in advance.)
> 

indeed, i care about geti's opinion because he actually knows what this game is supposed to be, unlike players with 1h/month, and i'm sure his arguments are going to actually make sense.



why do you think all the good old players left? do you really want to keep an infinite wave of newbies that quit because this game is too hard for them and punish the good players? good players got tired of all the broken mechanics and trying to cater to terraria/minecrafter players - quarries and shit like this. i really don't see the point in trying to ignore good players and pretending they aren't the most loyal players who care about it the most...

**Comment by blackjoker77777** [comment]
> I can't take you seriously when you don't even play the game and yet decide to voice your opinion on about everything

So you're saying that I'm not allowed to share my point of view because you think that I "don't even play the game"? (what do you think is the point in me constantly testing new changes if I wasn't playing?)..

Do you really think I'd waste my time and energy typing what I had in mind, if I didn't really care about this game?
Anyway, if my opinion wasn't to be respected, let it be.
Good luck shaping KAG into whatever kind of hell you want it to become.
I'm out.

**Comment by bunniewormy** [comment]
people like getting punished for having bad teammates so I guess this'll stay
