### ISSUE TITLE
Remove the halloween event

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#722]
**Current in-game behaviour.**

The current halloween event (gregs) causes significant lag on official servers, making the ground get buggy and increasing the amount of no anims. Moreover I don't believe the gregs are even that fun, especially if they just instakill you and you have no way of defending yourself against them

**Proposed Change**

Fix or remove

**Comment by CatWiz** [comment]
While i agree that current implementation is not that good because of all the lag and gregs being broken in general, i dont think that straight up removing halloween event is a good idea. Its one of few little things that add some variety to kag, even if it ruins balance. 
I think that halloween event should be reworked instead:

- Replace gregs with zombies crawling out of the ground every few minutes. Just like gregs, zombies will be hostile to everything, but they wont be unkillable while still being a threat to players. 
- Current death effect with ghost animation and sound is a nice touch, but it is rather annoying to hear it every time someone changes class. It should only play when someone actually dies.
- Have dead players fly around as ghosts until they respawn.

**Comment by bunniewormy** [comment]
I guess this should be brought up in September/early October next year if game will still be alive
