### ISSUE TITLE
Revert drill changes to state from a few months ago (apart from the QOL ones)

### ISSUE THREAD

**Issue by bunniewormy** [transhumandesign/kag-base#748]
Since we can't come to a consensus on what should be done with drills (people suggested some ridiculous nerfs to drills' combat worth while the buffs mainly gave ratters a huge advantage, not offensive builders), drills should be reverted to the state they were in before (faster overheat, 50% of stone yield instead of 100%). I originally suggested something in between current drills and old drills (mainly nerf drilling natural blocks, because rats, maybe slower cooldown) but apparently certain somebody decided this would need further discussion which caused any drill changes to be delayed for 2 months  :woman_shrugging:

**Comment by Panky123** [comment]
You shouldn't be able to hit a knight with a drill without them being able to slash you. Due to the drill being a pointed hit(whereas a slash is an arc) builders can drill thru an opening in doors while being shielded from enemy knights attack. Until this is fixed offensive drilling is low iq, busted, and easily abused.

**Comment by Trumbles** [comment]
I'm an oldfag so I am partial to this. I don't know what the general consensus is, however.

**Comment by Vam-Jam** [comment]
@bunniewormy do you want this to stay up after the recent drill changes or close it
