### ISSUE TITLE
Highlighting attacked objects w/ smooth shader causes shader issues.

### ISSUE THREAD

**Issue by Harrison-Miller** [transhumandesign/kag-base#776]
![image](https://user-images.githubusercontent.com/2775830/75311150-82cc2680-581b-11ea-9221-00eca8d03546.png)

Steps:
* Open sandbox
* Enable smooth shader
* Chop tree.

**Comment by AsuMagic** [comment]
Probably some z buffer bullcrap

**Comment by MonkeyFeats** [comment]
This is caused by RenderStyle::outline, Line 247 BuilderAnim.as

**Comment by AsuMagic** [comment]
Investigated this, it is because render target switching resets the Z buffer in Irrlicht (contrary to what the documentation says). There doesn't seem to be a way to fix that easily, so I suppose an approach would be to move that kind of outline rendering to before the render target swap (which would make more sense anyway), but that would interfere with the rest of rendering most likely...

**Comment by eps0003** [comment]
This is caused by the issues stated in #89
