### ISSUE TITLE
Change the way joining the game and spectators work.

### ISSUE THREAD

**Issue by CatWiz** [transhumandesign/kag-base#827]
1. Make spectators not count towards server player count.
2. If a server is full, you can still join, but you are forced into spectator team.
3. Unless you're an admin or high tier patreon supporter, you cant change your team from spectator to blue/red if a server is full (but you'll be able to go spec from blue/red).
This would allow players to spectate matches without wasting a player slot and preventing others from playing the game.

**Comment by Harrison-Miller** [comment]
it's a nice idea but there still needs to be a cap, because spectators tax a server almost as much as everyone else. The game is still receiving and sending data.

**Comment by CatWiz** [comment]
There certainly should be a limit, but from what i've seen spectators dont cause nearly as much lag as active players.

**Comment by furai** [comment]
@jrgp and any game server host will want to have option for it. Spectators must count towards total number of slots bought by a user.

**Comment by Pikamander2** [comment]
Spectator slots would be great.

If they don't work out for whatever reason, then we should at least add some kind of "auto join" button on the server menu that joins as soon a slot opens up.

Currently, joining a full server is very tedious since you basically just have to keep joining over and over again until it doesn't kick you.
