### ISSUE TITLE
Feature Pitch: Improve failure rate of knight animations

### ISSUE THREAD

**Issue by benjamingorman** [transhumandesign/kag-base#97]
Knight animations don't always display properly. This is a major source of frustration for knight players, since it makes it extremely difficult to fight properly. Being killed from full health by someone who looks like they're just shielding is a negative experience, since it's almost impossible to play around. Over the past few builds it seems that the issue has worsened for some reason. I'd estimate that around 50% of 1v1 fights right now come with some kind of animation failure. The issue mostly affects competitive players who are interested in TDM, tournaments or the 1v1 format.

I'll summarize the main types of animation failure (video clips coming soon):

1. A double slash appears as two jabs
2. A single slash appears as one jab
3. A double slash/slash occurs when someone appears to be shielding
4. Idle animation plays while someone is charging a slash.
5. Stun animation shows when someone is not actually stunned (often they are actually jabbing, or shielding). This can very easily lead to death: Suppose player A appears to be stunned but is actually shielding. Player B then thinks "ok - enemy is stunned, i'll jab them". However, since player A is actually shielding, player B then becomes stunned due to his jab and gets killed as a result.
6. When joining a game (usually CTF) sometimes particularly players are stuck in the stun animation until they are killed. If they're not killed for a long time, this can be problematic. However this is the least important form of animation failure since it doesn't affect the game for long.

The fact that animation failure only seems to affect the knight class suggests that maybe fixing this doesn't require engine changes, just changes to the knight animation script. However this might not be true.

Some other points to note:

- Often **sounds will correctly play** when animations don't. For example, in the case of failure type **4**, the associated sound `SwordSheath.ogg` still plays at the correct time. I think this is quite an important point to note because obviously the client _knows_ that the slash is occurring, or it wouldn't be able to play the correct sound. Obviously there are some cases where the client does not know the correct state of the game due to a laggy connection or packet loss etc. But in this instance that is not always the case.
- The rate of animation failure seems to increase for players with worse ping, however the issue is still present even for players with extremely good ping (like 10ms).

It may be impossible to completely eliminate this issue, due to the inherent limitations of networked games. Fixing this will be a challenge, since the issue happens intermittently and without much pattern (so it seems). But hopefully we can significantly improve the rate of failure, particularly with cases where sounds play correctly but animations don't. Personally I feel this is the biggest issue in game at the moment.

**Comment by makmoud98** [comment]
Biggest issue in the game by far. I know a handful of players who have quit from this issue alone.

**Comment by deynarde** [comment]
I agree, this issue takes away the pleasure of playing knight, especially with higher ping.

**Comment by nylyyy** [comment]
Yeah, this really affects the game in a big way and almost every time play I encounter it. I never knew what it had to do with but it's quite the issue, it was most prevalent for me while playing on my 1v1 server.

**Comment by Biurza** [comment]
Indeed biggest issue by now.
Not sure if it's worth mentioning, but sometimes, even when you jab your enemy with any other but sheild animation, sparkles will also display properly, making you understand that enemy was sheilding all along.
Same with shield sliding when you can't see it.

**Comment by Mcrifel** [comment]
This causes 90% of my rage quits. It is a serious issue, especially for the more competitive knights. I don't know you'd even go about fixing such a thing but if there is way it is definitely worth the effort.

**Comment by MuchSham-SuchWow** [comment]
I blame animations for all my problems. Thank you for bringing this up Eluded!

**Comment by fzzle** [comment]
Easiest fix by far (I sketched this up before and it worked great) is to foward times of the events and then calculate how far behind the client is. Say, LMB is pressed at 14:00:00 (server-side), the client recieves this information at 14:00:02 and notices that it's been 2 seconds since the actual event. The animation should then be started 2 seconds in (for example, set `.swordTimer` to 2x30 initially).

It's not relevant to show what's already happened, but that's how it is now. End events (for example, LMB "unpressed") will currently terminate the delayed animation (which causes broken animations / missing sounds). Instead it should show what's happening.

For perfect results, there's a bit more to it.

1k$ and the implementation is yours.

**Comment by blackiceball** [comment]
Hopefully this gets fixed soon.

**Comment by benjamingorman** [comment]
Lots of the issues can be seen in this video

https://www.youtube.com/watch?time_continue=25&v=jSoS0-3Z11o

**Comment by 1bardesign** [comment]
Thanks for the thorough report, we'll see what we can do.

Some of this is probably beyond the reach of non-engine contributions but should this turn out to be the most-requested change we'll happily work with contributors on the bounty and investigate any engine changes that could help alleviate the issue.

**Comment by bunniewormy** [comment]
I've made an account just to +1 this. honestly, this should be 300% priority right now. I'm having less and less fun each month, both from pubs and competitive kag, because of no animations. there are people who get 50% of their kills from constantly having broken anims. It's even worse for me, because I play without sound [I need to listen to music 2 b good] and I don't even hear when there's a broken anim

**Comment by Frankulushus** [comment]
I've been wanting a fix on this for so long, same with the 'infinite stun frame' problem.

**Comment by AsuMagic** [comment]
The infinite stun frame bug is a separate issue, I don't exactly know what causes it but @1bardesign knows better I think? Related to legacy freeze stuff or something like that.

**Comment by MrPotatobird** [comment]
https://youtu.be/5rEF-Hb43WQ

1. Enemy jabs shield + gets knocked right when I was done slashing; does NOT get knocked anim

2. Enemy jabs me while I'm charging a slash, I am in shield animation when my JAB hits him (I never jabbed on my screen)

3.1. I jab an enemy, he starts shielding but jabs back right before I start shielding. Visually, the jab damages me while I'm shielding and knocks enemy (he's not actually knocked, and the sparks + noise come a 2nd time when he then actually jabs my shield.)

3.2. After being knocked but not appearing knocked in 3.1, enemy jabs me out of shield without appearing to jab, gets knocked, and instead of appearing knocked, appears shielded and then appears to jab twice.

4. I jab an enemy who immediately jabs back right before I start shielding. No sound + sparks. I take damage, but their blob moves like it was knocked, and apparently from their perspective, they just got knocked, and maybe didn't even see me get damaged? I know health bars can desync too

5.1. I attempt to jab out of shield before getting slashed + start my jab animation, but the slash does effectively hit me and I get knocked + visually knocked, but when I come out of knock I'm still in my jab animation for a bit.

5.2 Jab enemy, immediately start shielding, he jabs back and I take damage but shield sound + sparks happen and he appears knocked, then shield sound + sparks play a second time when he actually jabs my shield and gets knocked

**Comment by AsuMagic** [comment]
verra god

**Comment by bunniewormy** [comment]
VERRA GOD PRAISE THE SUN URAAAAAA BUBUBUBUBUBU
